services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - "start-dev"