--\       Ingredient       /--
INSERT INTO ingredient (name, unity_type)
VALUES ('Flour', 'GRAM'),
       ('Sugar', 'GRAM'),
       ('Salt', 'GRAM'),
       ('Baking powder', 'GRAM'),
       ('Baking soda', 'GRAM'),
       ('Butter', 'GRAM'),
       ('Eggs', 'PIECE'),
       ('Whole milk', 'LITER'),
       ('Skim milk', 'LITER'),
       ('Almond milk', 'LITER'),
       ('Soy milk', 'LITER'),
       ('Coconut milk', 'LITER'),
       ('Vanilla extract', 'MILLILITER'),
       ('Chocolate chips', 'GRAM'),
       ('Chocolate bars', 'GRAM'),
       ('Cocoa powder', 'GRAM'),
       ('Vegetable oil', 'LITER'),
       ('Olive oil', 'LITER'),
       ('Canola oil', 'LITER'),
       ('Coconut oil', 'LITER'),
       ('Heavy cream', 'LITER'),
       ('Whipping cream', 'LITER'),
       ('Sour cream', 'GRAM'),
       ('Honey', 'MILLILITER'),
       ('Almonds', 'GRAM'),
       ('Walnuts', 'GRAM'),
       ('Pecans', 'GRAM'),
       ('Peanuts', 'GRAM'),
       ('Apples', 'PIECE'),
       ('Bananas', 'PIECE'),
       ('Strawberries', 'GRAM'),
       ('Blueberries', 'GRAM'),
       ('Raspberries', 'GRAM'),
       ('Oranges', 'PIECE'),
       ('Lemons', 'PIECE'),
       ('Carrots', 'GRAM'),
       ('Spinach', 'GRAM'),
       ('Onions', 'GRAM'),
       ('Tomatoes', 'GRAM'),
       ('Bell peppers', 'GRAM'),
       ('Cinnamon', 'GRAM'),
       ('Nutmeg', 'GRAM'),
       ('Ginger', 'GRAM'),
       ('Cloves', 'GRAM'),
       ('Paprika', 'GRAM'),
       ('Basil', 'GRAM'),
       ('Parsley', 'GRAM'),
       ('Cilantro', 'GRAM'),
       ('Rosemary', 'GRAM'),
       ('Thyme', 'GRAM'),
       ('Ketchup', 'MILLILITER'),
       ('Mustard', 'MILLILITER'),
       ('Mayonnaise', 'MILLILITER'),
       ('Soy sauce', 'MILLILITER'),
       ('Worcestershire sauce', 'MILLILITER');

--\       Category       /--
INSERT INTO category (name)
VALUES
    ('Italian'),
    ('Mexican'),
    ('Chinese'),
    ('Indian'),
    ('Japanese'),
    ('French'),
    ('Thai'),
    ('Spanish'),
    ('Greek'),
    ('Mediterranean'),
    ('American'),
    ('Middle Eastern'),
    ('Korean'),
    ('Vietnamese'),
    ('Brazilian'),
    ('Caribbean'),
    ('African'),
    ('British'),
    ('German'),
    ('Russian'),
    ('Scandinavian'),
    ('Cajun/Creole'),
    ('Filipino'),
    ('Indonesian'),
    ('Malaysian'),
    ('Turkish'),
    ('Lebanese'),
    ('Moroccan'),
    ('Peruvian'),
    ('Argentine');
